version: '3.9'
services:
    db:
        image: mysql:8
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=mysql
        volumes:
            - mysql:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    app:
        build: .
        environment:
            - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:mysql@db/test
        links:
            - "db"
        depends_on:
            - "db"
        ports:
            - "3000:3000"
volumes:
    mysql: